import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const stylePresets = [
  {
    name: 'realistic',
    label: 'Realistic',
    category: 'Photography',
    description: 'Photorealistic images with natural lighting',
    promptPrefix: 'photorealistic, highly detailed, 8k uhd, professional photography, natural lighting,',
    promptSuffix: 'sharp focus, realistic textures, lifelike',
    negativePrompt: 'cartoon, anime, painting, illustration, 3d render, deformed, blurry',
    colorAccent: '#f59e0b',
    model: 'flux-dev',
    cfgScale: 7.5,
    steps: 30,
  },
  {
    name: 'anime',
    label: 'Anime',
    category: 'Art',
    description: 'Japanese anime and manga style artwork',
    promptPrefix: 'anime style, manga illustration, vibrant colors, detailed anime art,',
    promptSuffix: 'studio ghibli inspired, clean lines, expressive',
    negativePrompt: 'photorealistic, 3d render, western cartoon, blurry, low quality',
    colorAccent: '#ec4899',
    model: 'flux-dev',
    cfgScale: 7.0,
    steps: 28,
  },
  {
    name: 'cinematic',
    label: 'Cinematic',
    category: 'Photography',
    description: 'Movie-quality cinematic shots',
    promptPrefix: 'cinematic shot, film still, dramatic lighting, depth of field, anamorphic lens,',
    promptSuffix: 'color graded, movie scene, epic composition',
    negativePrompt: 'snapshot, amateur, overexposed, underexposed, flat lighting',
    colorAccent: '#3b82f6',
    model: 'flux-dev',
    cfgScale: 7.0,
    steps: 35,
  },
  {
    name: 'fantasy',
    label: 'Fantasy',
    category: 'Art',
    description: 'Magical fantasy worlds and creatures',
    promptPrefix: 'fantasy art, magical atmosphere, ethereal lighting, mystical,',
    promptSuffix: 'detailed fantasy world, imaginative, otherworldly',
    negativePrompt: 'modern, urban, mundane, photorealistic, boring',
    colorAccent: '#10b981',
    model: 'flux-dev',
    cfgScale: 7.5,
    steps: 32,
  },
  {
    name: 'fashion',
    label: 'Fashion',
    category: 'Photography',
    description: 'High-end fashion photography',
    promptPrefix: 'fashion photography, haute couture, editorial, runway,',
    promptSuffix: 'stylish, trendy, designer clothing, vogue style',
    negativePrompt: 'casual, sloppy, outdated, poorly dressed',
    colorAccent: '#8b5cf6',
    model: 'flux-dev',
    cfgScale: 7.0,
    steps: 30,
  },
  {
    name: 'cartoon',
    label: 'Cartoon',
    category: 'Art',
    description: 'Fun cartoon and comic style',
    promptPrefix: 'cartoon style, vibrant colors, playful, fun illustration,',
    promptSuffix: 'clean vector style, bold outlines, cheerful',
    negativePrompt: 'realistic, dark, scary, photorealistic, 3d render',
    colorAccent: '#fbbf24',
    model: 'flux-dev',
    cfgScale: 7.0,
    steps: 25,
  },
  {
    name: 'cyberpunk',
    label: 'Cyberpunk',
    category: 'Art',
    description: 'Neon-lit futuristic cyberpunk scenes',
    promptPrefix: 'cyberpunk, neon lights, futuristic city, dystopian, holographic,',
    promptSuffix: 'blade runner style, high tech, rain, reflections',
    negativePrompt: 'pastoral, rural, natural, low tech, medieval',
    colorAccent: '#06b6d4',
    model: 'flux-dev',
    cfgScale: 7.5,
    steps: 35,
  },
  {
    name: 'portrait',
    label: 'Portrait',
    category: 'Photography',
    description: 'Professional portrait photography',
    promptPrefix: 'professional portrait, studio lighting, headshot,',
    promptSuffix: 'sharp eyes, skin detail, flattering light, bokeh background',
    negativePrompt: 'full body, landscape, group photo, blurry face',
    colorAccent: '#f43f5e',
    model: 'flux-dev',
    cfgScale: 7.0,
    steps: 30,
  },
  {
    name: 'pixel',
    label: 'Pixel Art',
    category: 'Art',
    description: 'Retro pixel art style',
    promptPrefix: 'pixel art, 16-bit, retro game style,',
    promptSuffix: 'dithering, limited palette, crisp pixels',
    negativePrompt: 'smooth, gradient, photorealistic, 3d, anti-aliased',
    colorAccent: '#22c55e',
    model: 'flux-dev',
    cfgScale: 7.0,
    steps: 25,
  },
  {
    name: '3d',
    label: '3D Render',
    category: 'Art',
    description: 'High-quality 3D rendered images',
    promptPrefix: '3d render, octane render, unreal engine 5, cgi,',
    promptSuffix: 'ray tracing, subsurface scattering, physically based rendering',
    negativePrompt: '2d, flat, hand drawn, sketch, painting',
    colorAccent: '#0ea5e9',
    model: 'flux-dev',
    cfgScale: 7.5,
    steps: 35,
  },
  {
    name: 'editorial',
    label: 'Editorial',
    category: 'Photography',
    description: 'Magazine editorial photography',
    promptPrefix: 'editorial photography, magazine cover, high fashion,',
    promptSuffix: 'professional lighting, polished, sophisticated',
    negativePrompt: 'casual, snapshot, amateur, poor composition',
    colorAccent: '#64748b',
    model: 'flux-dev',
    cfgScale: 7.0,
    steps: 30,
  },
  {
    name: 'product',
    label: 'Product',
    category: 'Photography',
    description: 'Clean product photography',
    promptPrefix: 'product photography, white background, studio shot, commercial,',
    promptSuffix: 'clean, minimal, professional product shot, sharp detail',
    negativePrompt: 'busy background, cluttered, dark, shadowy',
    colorAccent: '#a8a29e',
    model: 'flux-dev',
    cfgScale: 7.0,
    steps: 30,
  },
  {
    name: 'glamour',
    label: 'Glamour',
    category: 'Mature',
    description: 'Glamour and boudoir photography (18+)',
    promptPrefix: 'glamour photography, elegant, sophisticated,',
    promptSuffix: 'artistic, tasteful, professional lighting',
    negativePrompt: 'explicit, vulgar, amateur, poor quality',
    colorAccent: '#be185d',
    model: 'flux-dev',
    cfgScale: 7.0,
    steps: 30,
    isMature: true,
  },
  {
    name: 'boudoir',
    label: 'Boudoir',
    category: 'Mature',
    description: 'Artistic boudoir photography (18+)',
    promptPrefix: 'boudoir photography, intimate, artistic, soft lighting,',
    promptSuffix: 'elegant, tasteful, professional, romantic atmosphere',
    negativePrompt: 'explicit, crude, unprofessional, harsh lighting',
    colorAccent: '#831843',
    model: 'flux-dev',
    cfgScale: 7.0,
    steps: 30,
    isMature: true,
  },
];

async function main() {
  console.log('Seeding style presets...');

  for (const preset of stylePresets) {
    await prisma.stylePreset.upsert({
      where: { name: preset.name },
      update: {},
      create: preset,
    });
  }

  console.log(`Seeded ${stylePresets.length} style presets.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
